export const organisation = [
  {
    id: 1,
    firstName: "Mukesh Kumar",
    img: "public/assets/Zomato_logo.png",
    companyName: "Zomato",
    date: "22/08/2023",
    senderName: "Jayant Yadav",
    senderPost: "Bengaluru",
    senderEmail: "jayantyadav@gmail.com",
    senderPhone: "9406122813",
  },
  {
    id: 2,
    firstName: "Suresh Kumar",
    img: "public/assets/Zomato_logo.png",
    companyName: "Zomato",
    date: "02/09/2023",
    senderName: "Jitesh Sharma",
    senderPost: "Hubli",
    senderEmail: "jiteshsharma@gmail.com",
    senderPhone: "9752157403",
  },
  {
    id: 3,
    firstName: "Alakh Pandey",
    img: "public/assets/Zomato_logo.png",
    companyName: "Zomato Private Limited",
    date: "13/09/2023",
    senderName: "Dhruv Rathore",
    senderPost: "Delhi",
    senderEmail: "dhruvrathore121@gmail.com",
    senderPhone: "9406123423",
  },
  {
    id: 4,
    firstName: "Gopinanth Nanda",
    img: "public/assets/Zomato_logo.png",
    companyName: "Zomato",
    date: "03/09/2023",
    senderName: "Ashish Kumar",
    senderPost: "Chennai",
    senderEmail: "ashishkumar@gmail.com",
    senderPhone: "9424275786",
  },
  {
    id: 5,
    firstName: "Alok Nath",
    img: "public/assets/Zomato_logo.png",
    companyName: "Zomato",
    date: "27/08/2023",
    senderName: "Jay Rathee",
    senderPost: "Kanpur",
    senderEmail: "jayrathee23@gmail.com",
    senderPhone: "9406122323",
  },
];

export default organisation;
